name: 5ms_0-75ms
dark_mtz: data/olpvr1_esrf/5ms_0-75ms/ground.mtz
triggered_mtz: data/olpvr1_esrf/5ms_0-75ms/5ms_0-75ms.mtz
pdb_dark: data/olpvr1_esrf/5ms_0-75ms/olpvr1_id30a3_dark_refine_031.pdb
output_dir: results/olpvr1_esrf/5ms_0-75ms
resolution_limit: 2.2
columns:
  dark:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
  triggered:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
