name: esrf_5ms_2
dark_mtz: data/olpvr1_esrf/esrf_5ms_2/ground.mtz
triggered_mtz: data/olpvr1_esrf/esrf_5ms_2/5ms_37p5-75ms.mtz
pdb_dark: data/olpvr1_esrf/esrf_5ms_2/OLPVR1_id30a3_ground_refine_8.pdb
output_dir: results/olpvr1_esrf/esrf_5ms_2
resolution_limit: 2.2
columns:
  dark:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
  triggered:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
