name: esrf_5ms
dark_mtz: data/olpvr1_esrf/esrf_5ms/ground.mtz
triggered_mtz: data/olpvr1_esrf/esrf_5ms/5ms_0-37p5ms.mtz
pdb_dark: data/olpvr1_esrf/esrf_5ms/OLPVR1_id30a3_ground_refine_8.pdb
output_dir: results/olpvr1_esrf/esrf_5ms
resolution_limit: 2.2
columns:
  dark:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
  triggered:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
