name: trapping_1
dark_mtz: data/olpvr1_esrf/trapping_1/ground.mtz
triggered_mtz: data/olpvr1_esrf/trapping_1/6_CD364A_473nm_RT_5sec_5mWt.mtz
pdb_dark: data/olpvr1_esrf/trapping_1/olpvr1_high_res_refine_72.pdb
output_dir: results/olpvr1_esrf/trapping_1
resolution_limit: 1.13
columns:
  dark:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
  triggered:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
scaling_loss: huber_safe
