name: 30ms
dark_mtz: data/olpvr1_xfel/30ms/ground.mtz
triggered_mtz: data/olpvr1_xfel/30ms/30ms.mtz
pdb_dark: data/olpvr1_xfel/30ms/olpvr1_xfel_dark_refine_007.pdb
output_dir: results/olpvr1_xfel/30ms
resolution_limit: 1.97
columns:
  dark:
    kind: intensity
    amplitude_or_intensity: I
    sigma: SIGI
  triggered:
    kind: intensity
    amplitude_or_intensity: I
    sigma: SIGI
