name: 5us
dark_mtz: data/olpvr1_xfel/5us/ground.mtz
triggered_mtz: data/olpvr1_xfel/5us/5us.mtz
pdb_dark: data/olpvr1_xfel/5us/olpvr1_xfel_dark_refine_007.pdb
output_dir: results/olpvr1_xfel/5us
resolution_limit: 1.8
columns:
  dark:
    kind: intensity
    amplitude_or_intensity: I
    sigma: SIGI
  triggered:
    kind: intensity
    amplitude_or_intensity: I
    sigma: SIGI
