general:
  name_machine: 10ns
  name_human: 10ns
  output_folder: results/it_tv_extrapolated_maps
  plot_folder: results/it_tv_extrapolated_maps/10ns
  high_resolution_limit: 2.1
  comparison_type: triggered
input_files:
  map_dark: initial/10ns/ground.mtz
  map_triggered: initial/10ns/10ns.mtz
  pdb_dark: initial/10ns/OLPVR1_eufel_newsg_dark_refine_011.pdb
  impose_dark_phases: true
  columns_are_ints: true
  columns_dark_ints:
    ints_column: I
    int_uncertainty_column: SIGI
  columns_triggered_ints:
    ints_column: I
    int_uncertainty_column: SIGI
map_processing:
  diffmap_type: it_tv
  dark_mean_correction: true
  simple_dark_correction: true
  calculate_diffmap_before_f000: false
plot:
  show_plot: false
  save_to_file: true
