(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Dmitrii, Welcome to Coot version 0.9.8")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Dmitrii. Welcome to Coot 0.9.8")
(set-display-lists-for-maps 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/dmitrii/projects/tv_extrapolation/initial/5us/olpvr1_xfel_dark_refine_007.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz")
(make-and-draw-map-with-reso-with-refmac-params "/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz" "/reciprocalspaceship/reciprocalspaceship/F" "/reciprocalspaceship/reciprocalspaceship/PHI" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(graphics-molecule-bond-type 0)
(close-molecule 2)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
(graphics-molecule-bond-type 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
(graphics-molecule-bond-type 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector "/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
