filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Dmitrii, Welcome to Coot version 0.9.8")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Dmitrii. Welcome to Coot 0.9.8")
set_display_lists_for_maps (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/home/dmitrii/projects/tv_extrapolation/initial/5us/olpvr1_xfel_dark_refine_007.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz")
make_and_draw_map_with_reso_with_refmac_params ("/home/dmitrii/projects/tv_extrapolation/initial/5us/extrapolated_best_guess_diffmap_ittv.mtz", "/reciprocalspaceship/reciprocalspaceship/F", "/reciprocalspaceship/reciprocalspaceship/PHI", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
graphics_molecule_bond_type (0)
close_molecule (2)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
graphics_molecule_bond_type (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
graphics_molecule_bond_type (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector ("/home/dmitrii/projects/tv_extrapolation/initial/5us/ground.mtz")
