name: ech_laser_30min
dark_mtz: data/ocp_ech/dark/dimple_processing/ech-dark_dimple.mtz
triggered_mtz: data/ocp_ech/ech_laser_30min/dimple_processing/ech-laser_30min_dimple.mtz
pdb_dark: data/ocp_ech/OCP_ECH_dark.pdb
output_dir: results/ocp_ech/ech_laser_30min
resolution_limit: 1.8
columns:
  dark:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
  triggered:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
