name: ocp_oldflip_maxiv
dark_mtz: data/ocp_ech/ocp_oldflip_maxiv/ech-full_dark_dimple.mtz
triggered_mtz: data/ocp_ech/ocp_oldflip_maxiv/ech-laser_dimple.mtz
pdb_dark: data/ocp_ech/ocp_oldflip_maxiv/ECH_MAXIV_dark_new_prefin.pdb
output_dir: results/ocp_ech/ocp_oldflip_maxiv
resolution_limit: 1.66
columns:
  dark:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
  triggered:
    kind: amplitude
    amplitude_or_intensity: F
    sigma: SIGF
