name: ocp_firstprocessing_1h
dark_mtz: data/ocp_ech/ocp_firstprocessing/dark.mtz
triggered_mtz: data/ocp_ech/ocp_firstprocessing/1hlight.mtz
pdb_dark: data/ocp_ech/ocp_firstprocessing/dark_ech_reference.pdb
output_dir: results/ocp_ech/ocp_firstprocessing_1h
scaling_loss: huber_safe
resolution_limit: 1.24
columns:
  dark:
    kind: intensity
    amplitude_or_intensity: IMEAN
    sigma: SIGIMEAN
  triggered:
    kind: intensity
    amplitude_or_intensity: IMEAN
    sigma: SIGIMEAN
