general:
  name_machine: ech_laser_30min
  name_human: ech_laser_30min
  output_folder: results/it_tv_ocp
  plot_folder: results/it_tv_ocp/ech_laser_30min
  high_resolution_limit: 1.8
  comparison_type: triggered
input_files:
  map_dark: results/it_tv_ocp/ech_laser_30min/ech_laser_30min_dark_finite.mtz
  map_triggered: results/it_tv_ocp/ech_laser_30min/ech_laser_30min_triggered_finite.mtz
  pdb_dark: results/it_tv_ocp/ech_laser_30min/ech_laser_30min_dark_cell.pdb
  impose_dark_phases: true
  columns_are_ints: false
  columns_dark:
    amplitude_column: F
    phase_column: MODEL
    uncertainty_column: SIGF
  columns_triggered:
    amplitude_column: F
    phase_column: MODEL
    uncertainty_column: SIGF
map_processing:
  diffmap_type: it_tv
  dark_mean_correction: true
  simple_dark_correction: true
  calculate_diffmap_before_f000: false
plot:
  show_plot: false
  save_to_file: true
