filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Dmitrii, Welcome to Coot version 0.9.8")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Dmitrii. Welcome to Coot 0.9.8")
set_display_lists_for_maps (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/home/dmitrii/projects/tv_extrapolation/results/it_tv_extrapolated_maps/5us/refine_adp/5us_it_tv_dry_adp_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
