(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Dmitrii, Welcome to Coot version 0.9.8")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Dmitrii. Welcome to Coot 0.9.8")
(set-display-lists-for-maps 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/dmitrii/projects/tv_extrapolation/results/it_tv_extrapolated_maps/5us/refine_adp/5us_it_tv_dry_adp_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
